name: Windows Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'   # 8 AM Bangladesh

permissions:
  contents: write

jobs:
  scrape:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: browser-actions/setup-chrome@v1

      - run: pip install -r requirements.txt

      - run: python scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add pornstars/*.txt
          git commit -m "Auto scraped txt files" || echo No changes
          git push
